# Generated by Django 3.1.4 on 2021-04-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('img', models.CharField(max_length=70)),
                ('price', models.FloatField(max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
