# Generated by Django 3.1.4 on 2021-04-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0002_auto_20210404_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
